### ISSUE TITLE
adding config for CORS

### ISSUE THREAD

**Issue by MuhAssar** [assafmo/SQLiteProxy#1]
Hi, thanks for your usefull tool

please add support to configer the CORS header to allow the requests from all origins '*'

**Comment by assafmo** [comment]
Can you describe how that would look like?  A config file? A CLI param?

Or I can just always allow `*` like I'm doing in SQLiteQueryServer: https://github.com/assafmo/SQLiteQueryServer/blob/f3e4d604aaeaccbaae737ebfab1053b0e37b066f/main.go#L100

**Comment by assafmo** [comment]
BTW if you're only doing queries you should really check out https://github.com/assafmo/SQLiteQueryServer because it's much faster.

**Comment by MuhAssar** [comment]
I checked your other repo SQLiteProxyServer but I’d like to continue with this one SQLiteProxy as it is in JS and I find it easier to install and run.

**Comment by MuhAssar** [comment]
regarding cors you may add a single flag --allow-cors with the following options:

\* to allow all origins or
**http://example1.com, http://example2.com** to whitelist these origins or
**default** to stay as it is now

https://expressjs.com/en/resources/middleware/cors.html for more details

**Comment by assafmo** [comment]
Okay let me see what can I do.

On the other repo you can also download a precompiled binary if it's easier: https://github.com/assafmo/SQLiteQueryServer/releases

**Comment by MuhAssar** [comment]
> Okay let me see what can I do.
> 
> On the other repo you can also download a precompiled binary if it's easier: https://github.com/assafmo/SQLiteQueryServer/releases

I checked the releases already but couldn't find a binary for mac os

**Comment by assafmo** [comment]
I just pushed v0.7.1 to npm & docker. Let me know how it works for you. :pray: 

I also compiled SQLiteQueryServer to Mac OS, you can check it out here: https://github.com/assafmo/SQLiteQueryServer/releases/download/v1.4.0/SQLiteQueryServer-v1.4.0-darwin-10.6-amd64.zip

**Comment by MuhAssar** [comment]
wonderful, I used --cors '*' and it works perfectly!

much appreciated

**Comment by MuhAssar** [comment]
I may also take a look for SQLiteProxyServer thanks for the mac os release!

**Comment by assafmo** [comment]
> I may also take a look for SQLiteProxyServer thanks for the mac os release!

Should be much faster :-)
